### ISSUE TITLE
Toán tử

### ISSUE THREAD

**Issue by piouscity** [piouscity/big_number#1]
Cộng, trừ, nhân, chia, and, or, xor, not, shift.
Cần gì thì bàn luận trong đây ha =]]

**Comment by JATC1024** [comment]
Operator + Qint với int. Nếu int>O thì ko vấn đề gì, trường hợp int<O thì làm sao?

**Comment by piouscity** [comment]
Đang check...

**Comment by piouscity** [comment]
### Bug 1
Phép so sánh > bị sai:
```
// 2^64 - 2^32
bool b0[128] = {};
for (int i = 32; i < 64; ++i) b0[i] = 1;

// 1
bool b1[128] = {};
b1[0] = 1;

QInt a0(b0);
QInt a1(b1);

cout << (a1 > a0);  //Xuất ra true
```
Hiển nhiên là các phương thức có sử dụng > < >= <= bị sai theo :)))

**Comment by piouscity** [comment]
Chắc là oke rồi :))
