### ISSUE TITLE
Xuất số QInt

### ISSUE THREAD

**Issue by JATC1024** [piouscity/big_number#3]
Dùng string để tính kết quả xong xuất?

**Comment by piouscity** [comment]
Không lẽ mình viết hàm cộng số dạng string? :/

**Comment by JATC1024** [comment]
Ngoài cách đó ra thì không nghĩ được cách nào khác. Để coi máy nó làm sao

**Comment by piouscity** [comment]
Thôi đừng viết hàm cộng string, nghe nó chuối quá.

**Comment by piouscity** [comment]
Lần lượt mod 10 và div 10 số đó.
Thực ra operator mod ko cần phức tạp như chia đâu, làm kiểu này cho dễ:
a div b = c
a mod b = r
=> a = b*c + r
(Số dương thôi, âm thì xét thêm lonh tinh gì đó)

**Comment by JATC1024** [comment]
Không hiểu lắm?

**Comment by piouscity** [comment]
10010 mod 1010 = 1000 (8)
10010 div 1010 = 1
1 mod 1010 = 1 (1)
1 div 1010 = 0 (dừng)
Kết quả là 18

**Comment by JATC1024** [comment]
Mod khong chia thì thực hiện như nào?

**Comment by piouscity** [comment]
Ủa có nói ko chia đâu, ý là mình kế thừa lại kết quả của phép chia chứ ko code lại cái phần chia rồi lấy phần dư.
a % b = a - (a/b)*b

**Comment by piouscity** [comment]
Phần xuất này chắc là quá ổn rồi (giả sử operator > đã được sửa). Move qua DONE nha.
