### ISSUE TITLE
6 hàm chuyển cơ số

### ISSUE THREAD

**Issue by nguyenkhacduc** [piouscity/big_number#6]

**Comment by JATC1024** [comment]
Quy ước khi lưu dữ trữ các số ở dạng binary, hexa thì đánh số từ 0, nghĩa là chữ số thứ i thì lưu ở vị trí thứ i trong mảng. Chỉ khi cần xuất ra cho người dùng thì mới đổi lại để xuất.

**Comment by nguyenkhacduc** [comment]
Ey nếu đánh số theo kiểu trên thì có bất cập là xâu truyền vào hàm ko biết có đúng thứ tự như mình đã quy ước hay chưa. Vd với hàm BinToDec(), có 2 yêu cầu khác nhau như thế này:
1. Chuyển đổi 1 số từ nhị phân sang QInt, số nhị phân được nhập vào từ input: lúc này xâu truyền vào hàm BinToDec() có chiều ngược với quy ước.
2. Chuyển đổi 1 số từ Hexa sang QInt: mình phải chuyển Hexa -> Bin, rồi từ Bin -> Dec, lúc này xâu truyền vào hàm BinToDec() lại có chiều đúng với quy ước.

Đề xuất cách sửa:
1. Đổi quy ước ngược lại 
2. Viết thêm hàm để xác định những phép toán nào sử dụng xâu truyền vào ngược với quy ước (BinToDec(), các phép toán +, -, *, / trên số nhị phân, ...), reverse nó lại.
3. Đề xuất khác :v

Vote đê !!!

**Comment by JATC1024** [comment]
Đâu thì cứ theo quy ước đó. Thằng nào dùng hàm của mình thì nó phải tự động biết đổi xâu ngược lại. Ví dụ lúc nhập, nhập xong muốn xài mấy cái chuyển đổi thì reverse xâu lại thôi, khỏi viết hàm xác định gì hết.

**Comment by JATC1024** [comment]
Còn muốn thật sự chuyên nghiệp thì làm vầy.
Tạo hai cái đối tượng Binary với Hexa. Trong hai đối tượng đó dữ liệu được lưu đánh số từ 0. Như vậy các hàm chuyển đổi sẽ không nhận tham số là string nữa mà là Binary với Hexa, ví dụ Hexa BinToHex(Binary).
Tất nhiên là như QInt, hai đối tượng này sẽ có constructor chuyển đổi từ một số binary với hexa lưu ở dạng string (cái dạng mà mình nhìn thấy bằng mắt) sang Binary với Hexa.
Lúc nhập chả cần reverse gì hết.
Thấy cách này chuyên nghiệp nhất.

**Comment by piouscity** [comment]
Hàm gốc của mình là nhận mảng bool, theo thứ tự cũ
Mình viết thêm một hàm nữa nhận string (tại kiểu éo gì mình cũng dùng string để nhập mà phải ko), trong đó mình tạo mảng bool ngược lại với string, xong rồi gọi lại hàm gốc
Hexa cũng gọi lại hàm gốc

**Comment by JATC1024** [comment]
Mình có 3 loại cơ số là dec, hex và bin.
Dec mình lưu ở dạng QInt, hex với bin lưu dưới dạng string đánh số từ 0.
Khi nhập dữ liệu, các cơ số trên được lưu ở dạng string theo như mắt mình nhìn thấy (nghĩa là đánh số từ cao xuống thấp). Như vậy cần có hàm chuyển đổi từ dạng nhìn thấy này sang dạng mình lưu.
Qint có constructor chuyển từ string (dạng mắt nhìn) sang dạng được lưu, nên bất cứ khi nào mình truyền một string vô một cái QInt nó cũng tự động cast cho mình.
Hex với bin chỉ đơn giản là string nên nó ko có constructor, do đó mỗi lần muốn đổi từ dạng mắt nhìn sang dạng được lưu thì phải reverse.
Tất nhiên là mình có thể reverse mỗi lần mình dùng, nhưng t thấy thế hơi bất tiện, ngoài ra có thể quên reverse dẫn đến chạy sai.
Vì vậy, t muốn lưu hex với bin ở dạng khác chứ không phải là string, sau đó bất cứ hàm nào mà có dùng tham số hoặc trả về bin với hex thì mình overload lại hết. 
VÍ dụ:
````
QInt BinToDec(Binary x){
	// Du lieu danh so tu 0
}

QInt BinToDec(string x){
	reverse(x.begin(), x.end());
	Binary y;
	// Lam gi do de luu x vao y.
	return BinToDec(y);
}
````
Như vậy, hàm bintodec mà nhận string tham số là hàm xử lý trên dữ liệu dạng mắt nhìn. Mình ko cần reverse vì vào trong đó nó tự reverse rồi gọi hàm gốc.
Giờ thì vấn đề là Binary nên là cái gì? Nếu mình typedef binary thành string thì ko dc, do nó bị trùng chữ kí. Nếu typedef thành char * thì dc, nhưng mà nảy sinh vấn đề về bộ nhớ này nọ. Do đó t nghĩ tạo một class mới là tốt nhất. Khi đó không cần phải viết hàm BinToDec(string) luôn, bởi vì mình cun cấp constructor đổi từ dạng mắt nhìn sang dạng lưu trữ cho Binary với Hex luôn.

**Comment by nguyenkhacduc** [comment]
Đề xuất mang tính chắp vá: trong cả chương trình có mỗi cái hàm HexToDec() là xài xâu Bin giống với quy ước ban đầu, nên mình reverse nó trước khi đưa vào hàm BinToDec(), còn trong hàm BinToDec() thì có reverse trước khi chuyển đổi.
Code ví dụ minh họa:

QInt BinToDec(const string &bit)
{
	if (bit.size() > qSize)
		throw _SIZE_EXCEEDED;
	reverse(bit.begin(), bit.end());
        //do something ...
	return result;
}

QInt HexToDec(const string &hexa)
{
	if ((int)hexa.size() > (qSize >> 2))
		throw _SIZE_EXCEEDED;
	string bit = HexToBin(hexa);
        reverse(bit.begin(), bit.end());

	QInt result = BinToDec(bit);
	return result;
}

**Comment by JATC1024** [comment]
T không hiểu lắm?
Trong hextodec ông đánh số từ cao xuống thấp, xong reverse lại cho nó thành thấp lên cao rồi bỏ vô bintodec.
Vo bintodec đang thấp sang cao ông reverse lại cho thành cao xuống thấp lại??

**Comment by nguyenkhacduc** [comment]
trong hextodec() thì cái string bit đc đánh số phụ thuộc vào hàm hextobin(), nếu hextobin() từ thấp lên cao thì string bit trước khi đưa vào hàm bintodec() cũng từ thấp lên cao, nên t reverse trước khi đưa vào hàm bintodec(), rồi vào hàm bintodec() reverse lại lần nữa cho nó trở về dạng ban đầu (thấp lên cao) rồi xử lý

**Comment by nguyenkhacduc** [comment]
Thực tế thì cái hàm HexToBin() chỉ có duy nhất 1 công dụng là chuyển đổi từ HexToBin() thôi, ko có là hàm trung gian hay bất cứ 1 thao tác nào khác sử dụng cái hàm này hết, nên nếu hàm HexToBin() nhận vào string hexa ngược quy ước, thì mình có thể reverse thoải mái cho nó thuận rồi xử lý như bình thường.

**Comment by JATC1024** [comment]
T mới code lại mấy cái hàm chuyển đổi. Nãy thấy Hiếu nói đúng, mình lưu ở dạng QInt còn mấy cái hexa với binary này nọ chỉ là một dạng biểu diễn của nó lúc xuất ra thôi.
Thành ra t làm vầy
Trong class QInt, tạo mấy cái hàm ToHex, ToBin, FromHex, FromBin. Mấy hàm đó nhận tham số là một string (góc độ người dùng) sau đó lưu lại thành QInt hoặc xuất dữ liệu ra một string (góc độ người dùng). Hàm main chỉ việc nhập string sau đó gọi các hàm trên, đổi mọi thứ thành QInt là được.
