### ISSUE TITLE
Adapter 1

### ISSUE THREAD

**Issue by piouscity** [piouscity/big_number#9]
Cần thêm phương thức sau cho class QInt:
`void QInt::expor(uint16_t* base, uint16_t &extend);`
Hàm này trả về dữ liệu hiện có của (*this). Kết quả trả về được lưu vào 2 tham số. Trong đó:
- base là con trỏ trỏ tới mảng 7 phần tử đã được cấp phát sẵn, lưu 112 bit đầu tiên của số QInt. (từ bit 0 tới bit 111)
- extend dùng để lưu 16 bit còn lại của QInt.
- Quy ước: base[0] lưu từ bit 0 tới bit 15, base[1] lưu từ bit 16 tới bit 31...

**Comment by JATC1024** [comment]
Updated
